db_path: cad_db
demo_img_path: config/2014.jpg
db_file: config/db.sqlite3
pkl_file: config/ds_model.pkl
photo_db_dir: cad_db
dedup_similarity_threshold: 0.24 # 0.23
detector_backend: yolov11s
face_detection_threshold: 0.84
presentation_model_name: VGG-Face
# presentation_model_name: Facenet512

presentation_face_detector: yolov11m
presentation_expand_percentage: 0
presentation_sim_threshold: 0.3
workers: 1
worker_warm_up_time_ms: 100
presentation_distance_metric: cosine